# This is a basic workflow to help you get started with Actions

name: Actions-Workflow-testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test-1-files ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Building .java file
        working-directory : ./src/com/company/
        run: javac Main.java
      - name : Running .class file
        working-directory : ./out/production/git-Actions-Workflow/
        run : java com.company.Main
        
      - name : list of modified files
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G "$URL" | jq -r '.[] | .filename')
          echo "$FILES"
            
            
